### ISSUE TITLE
new function sorted_json does not work if keys are set to undef

### ISSUE THREAD

**Issue by bodepd** [solarkennedy/puppet-consul#59]
in the case where hash keys are explicitly set to undef, the following exception is encountered:

```
       undefined method `Exception' for #<Puppet::Parser::Scope:0x007fe77ec64d38> at /Users/danbode/dev/reliance/apply_resources/rjil/spec/fixtures/modules/consul/manifests/config.pp:35 on node danslaptop-2.local
     # ./spec/fixtures/modules/consul/lib/puppet/parser/functions/consul_sorted_json.rb:22:in `sorted_json'
     # ./spec/fixtures/modules/consul/lib/puppet/parser/functions/consul_sorted_json.rb:16:in `block in sorted_json'
     # ./spec/fixtures/modules/consul/lib/puppet/parser/functions/consul_sorted_json.rb:15:in `each'
     # ./spec/fixtures/modules/consul/lib/puppet/parser/functions/consul_sorted_json.rb:15:in `sorted_json'
     # ./spec/fixtures/modules/consul/lib/puppet/parser/functions/consul_sorted_json.rb:42:in `block in <module:Functions>'
     # ./spec/classes/jiocloud_spec.rb:37:in `block (3 levels) in <top (required)>'
```

**Comment by bodepd** [comment]
this was already merged in #60, closing
